### PR TITLE
Partner logo

### PR DESCRIPTION
**Pull request by svouse**

### CODE REVIEW

**Comment by svouse** [comment]
I noticed for all in that excludeFromPartnerList is flagged-- should this remain on?

**Comment by billylaing** [comment]
@svouse `excludeFromPartnerList = true` will prevent the logo from being show on the site.

**Comment by billylaing** [comment]
Also, I am guessing you already know this, but looks like you aren't branching off of `master` when you are making a new branch so the commit log for the PR has a lot of irrelevant entries.

**Comment by svouse** [comment]
Yup--I realized after a bunch of annoying checkouts-- I've updated this pr to unhide the all in logo

**Review by billylaing — APPROVED** [review]

**Pull request merged**
